// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw6V8a_sNbkFEfKVcUw23ViGgU7fZkync',
    appId: '1:539520125827:web:2a7ca62a1984872c6c44b6',
    messagingSenderId: '539520125827',
    projectId: 'motifa-batik-84a69',
    authDomain: 'motifa-batik-84a69.firebaseapp.com',
    storageBucket: 'motifa-batik-84a69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYk-6vn_J9VQVoCaMoROjch12cEYqq14',
    appId: '1:539520125827:android:c46313db875d9f8a6c44b6',
    messagingSenderId: '539520125827',
    projectId: 'motifa-batik-84a69',
    storageBucket: 'motifa-batik-84a69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzVRZnLqNOwnNl7jxglS4NS2LnVGk9EU4',
    appId: '1:539520125827:ios:c85a5cf089bc39286c44b6',
    messagingSenderId: '539520125827',
    projectId: 'motifa-batik-84a69',
    storageBucket: 'motifa-batik-84a69.firebasestorage.app',
    iosBundleId: 'com.example.motifa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzVRZnLqNOwnNl7jxglS4NS2LnVGk9EU4',
    appId: '1:539520125827:ios:c85a5cf089bc39286c44b6',
    messagingSenderId: '539520125827',
    projectId: 'motifa-batik-84a69',
    storageBucket: 'motifa-batik-84a69.firebasestorage.app',
    iosBundleId: 'com.example.motifa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw6V8a_sNbkFEfKVcUw23ViGgU7fZkync',
    appId: '1:539520125827:web:64716ef101948c9b6c44b6',
    messagingSenderId: '539520125827',
    projectId: 'motifa-batik-84a69',
    authDomain: 'motifa-batik-84a69.firebaseapp.com',
    storageBucket: 'motifa-batik-84a69.firebasestorage.app',
  );
}
