// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_aS-U5fw8UmFJdFf98TuvW3EJHT3gTQ',
    appId: '1:611583720956:web:35e204ca50d433201b8679',
    messagingSenderId: '611583720956',
    projectId: 'mynotes-ghazian',
    authDomain: 'mynotes-ghazian.firebaseapp.com',
    storageBucket: 'mynotes-ghazian.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1eeTyZ2_yLls9V-ux8rfAPOQALi4Iers',
    appId: '1:611583720956:android:3b52f59444ef08071b8679',
    messagingSenderId: '611583720956',
    projectId: 'mynotes-ghazian',
    storageBucket: 'mynotes-ghazian.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0T1xKMeTc3fV7An9JdcPmlTD-Wm51Fso',
    appId: '1:611583720956:ios:7bba530f71afcd0d1b8679',
    messagingSenderId: '611583720956',
    projectId: 'mynotes-ghazian',
    storageBucket: 'mynotes-ghazian.firebasestorage.app',
    iosBundleId: 'com.ghazian.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0T1xKMeTc3fV7An9JdcPmlTD-Wm51Fso',
    appId: '1:611583720956:ios:7bba530f71afcd0d1b8679',
    messagingSenderId: '611583720956',
    projectId: 'mynotes-ghazian',
    storageBucket: 'mynotes-ghazian.firebasestorage.app',
    iosBundleId: 'com.ghazian.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6_aS-U5fw8UmFJdFf98TuvW3EJHT3gTQ',
    appId: '1:611583720956:web:a3ce95730b8dc7ce1b8679',
    messagingSenderId: '611583720956',
    projectId: 'mynotes-ghazian',
    authDomain: 'mynotes-ghazian.firebaseapp.com',
    storageBucket: 'mynotes-ghazian.firebasestorage.app',
  );
}
